#pragma kernel CSMain
RWTexture2D<float4> Result;
float2 _TexelCount;
float4 _Lights[16];
uint _LightCount;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float darkIntensity = 1;
    float2 pixelOffset = id.xy;
    for (uint i = 0u; i < _LightCount;i++)
    {
        float2 lightPixel = _Lights[i].xy;
        float lightSQRRange = _Lights[i].z;
        float lightIntensity = _Lights[i].w;
        
        float2 offset = pixelOffset - lightPixel;
        float sqrDistance = dot(offset, offset);
        
        float intensity = pow(lightSQRRange/sqrDistance, 2) * lightIntensity;
        darkIntensity -= intensity;
    }
    Result[id.xy] =  float4(.1, .1, .1, darkIntensity);
}
